//Universidad Estatal a Distancia
//Vicerrectoría de Docencia
//Escuela de Ciencias Exactas y Naturales
//Cátedra de Desarrollo de sistemas
//Asignatura: SISTEMAS OPERATIVOS
//Código: 00881
// II CUATRIMESTRE 2025
//Estudiante: Héctor Andrés Arrieta Sancho
//Cédula: 114070263
//Proyecto final sistemas operativos
/// Proyecto de aula virtual que permite el registro, asignación y consulta de cursos,
/// gestionando accesos diferenciados para administradores y estudiantes.

package Ventanas;

import Entidades.Estudiante;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;


public class BuscarEstudiante extends javax.swing.JFrame {

    private String tipoUsuario;

    /**
     * Creates new form BuscarEstudiante
     */
    public BuscarEstudiante(String tipoUsuario) {
        initComponents();
        inicializarTablas(); 
         this.tipoUsuario = tipoUsuario;
    inicializar();
    setLocationRelativeTo(null);
    setResizable(false);
    
    cmbEstudiantes.addItemListener(e -> {
    if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        actualizarCedulaDesdeCombo();
    }
});
    try {
            Utilidades.UtilidadesGUI.configurarVentana(this, "/imagenes/fondobuscarestudiante.jpg");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar imagen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }

    ///
    ///inicializa los datos de la ventana: llena el combo de estudiantes.
    ///
    private void inicializar() {
    llenarComboEstudiantes();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbEstudiantes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiante = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel1.setText("Busqueda de estudiantes");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel2.setText("Seleccionar estudiante:");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel3.setText("Cédula del estudiante");

        btnBuscar.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEstudiante.setEnabled(false);
        jScrollPane1.setViewportView(tablaEstudiante);

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCursos.setEnabled(false);
        jScrollPane2.setViewportView(tablaCursos);

        btnVolver.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ///
        ///busca al estudiante por cédula y muestra sus datos y cursos asignados
        ///
        
         String cedula = txtCedula.getText().trim();

    if (cedula.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar o seleccionar una cédula.");
        return;
    }

    try {
        Estudiante est = AccesoADatos.ArchivoEstudiante.cargarEstudiantePorId(cedula);
        if (est == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Estudiante no encontrado.");
            return;
        }

        mostrarDatosEstudiante(est);
        mostrarCursosAsignados(cedula);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
          this.setVisible(false);
    VentanaAulaVirtual volver = new VentanaAulaVirtual(tipoUsuario);
    volver.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    ///
    ///llena el combo con todos los estudiantes registrados (ID + nombre completo)
    ///
    private void llenarComboEstudiantes() {
    cmbEstudiantes.removeAllItems(); //limpia el combo

    //agregar opción inicial
    cmbEstudiantes.addItem("Seleccione uno");

    File carpeta = new File("registros_estudiantes");
    if (!carpeta.exists()) {
        return;
    }

    File[] archivos = carpeta.listFiles();
    if (archivos == null) {
        return;
    }

    for (File archivo : archivos) {
        try {
            String id = archivo.getName().replace(".txt", "");
            Estudiante est = AccesoADatos.ArchivoEstudiante.cargarEstudiantePorId(id);
            if (est != null) {
                cmbEstudiantes.addItem(id + " - " + est.getNombre() + " " + est.getPrimerApellido());
            }
        } catch (Exception e) {
            
        }
    }

    // Dejar seleccionado el "Seleccione uno"
    cmbEstudiantes.setSelectedIndex(0);
}





///
///cando se selecciona un estudiante en el combo se llena el campo de cédula
///
private void cmbEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {
    String seleccionado = (String) cmbEstudiantes.getSelectedItem();
    if (seleccionado != null && seleccionado.contains(" - ")) {
        String id = seleccionado.split(" - ")[0];
        txtCedula.setText(id);
    }
}





    ///
    ///muestra los datos del estudiante en tablaEstudiante (una sola fila).
    ///
private void mostrarDatosEstudiante(Estudiante est) {
    String[] columnas = {"ID", "Nombre", "Apellido 1", "Apellido 2", "Nacimiento", "Email", "Teléfono"};
    Object[][] datos = {
        {
            est.getId(),
            est.getNombre(),
            est.getPrimerApellido(),
            est.getSegundoApellido(),
            est.getFechaNacimiento(),
            est.getEmail(),
            est.getTelefono()
        }
    };

    tablaEstudiante.setModel(new javax.swing.table.DefaultTableModel(datos, columnas));
}







///
///mestra los cursos asignados al estudiante en tablaCursos
///
private void mostrarCursosAsignados(String cedula) {
    List<String> cursos = AccesoADatos.ArchivoAsignacion.obtenerCursosAsignados(cedula);

    String[] columnas = {"Cursos asignados"};
    Object[][] datos = new Object[cursos.size()][1];

    for (int i = 0; i < cursos.size(); i++) {
        datos[i][0] = cursos.get(i);
    }

    tablaCursos.setModel(new javax.swing.table.DefaultTableModel(datos, columnas));
}







///
/// Toma el ítem seleccionado del combo y coloca la cédula en txtCedula
/// Acepta tanto "ID - Nombre Apellido" (String) como objeto Estudiante
///
private void actualizarCedulaDesdeCombo() {
    Object sel = cmbEstudiantes.getSelectedItem();
    if (sel == null) {
        return;
    }

    String seleccionado = sel.toString();
    if (seleccionado.equals("Seleccione uno")) {
        txtCedula.setText("");
        return;
    }

    int guion = seleccionado.indexOf(" - ");
    if (guion > 0) {
        txtCedula.setText(seleccionado.substring(0, guion).trim());
    }
}



  

    ///
    ///configura las columnas de las tablas para que se vean aunque no haya datos
    ///
private void inicializarTablas() {
    // tablaEstudiante: una sola fila cuando haya datos
    javax.swing.table.DefaultTableModel modeloEst = new javax.swing.table.DefaultTableModel(
        new Object[][]{}, 
        new String[]{"ID", "Nombre", "Apellido 1", "Apellido 2", "Nacimiento", "Email", "Teléfono"}
    ) {
        public boolean isCellEditable(int row, int col) { return false; }
    };
    tablaEstudiante.setModel(modeloEst);

    // tablaCursos: listado de cursos asignados
    javax.swing.table.DefaultTableModel modeloCursos = new javax.swing.table.DefaultTableModel(
        new Object[][]{}, 
        new String[]{"Cursos asignados"}
    ) {
        public boolean isCellEditable(int row, int col) { return false; }
    };
    tablaCursos.setModel(modeloCursos);

    // Opcional: bloquear mover columnas
    tablaEstudiante.getTableHeader().setReorderingAllowed(false);
    tablaCursos.getTableHeader().setReorderingAllowed(false);
}

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbEstudiantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCursos;
    private javax.swing.JTable tablaEstudiante;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
/*
Referencias bibliográficas
Academy, E. (24 de abril de 2023). youtube. Obtenido de https://www.youtube.com/watch?v=SXIOxvxWf7A
BOS, A. S. (2024). SISTEMAS OPERATIVOS. México: Pearson Educación de méxico.
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/vector-gratis/personas-que-van-universidad-fondo-rosa_9057638.htm#fromView=search&page=1&position=43&uuid=ed7ad1f5-f8a4-46b1-83c2-9724be9869a6&query=entorno+estudiantil+animado+minimalista
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/foto-gratis/concepto-escritorio-vista-superior-cafe_9216574.htm#fromView=image_search_similar&page=1&position=7&uuid=54a8cc55-3529-43e0-91d6-66f41a252e2a&query=fondo+registrarse+universidad
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/foto-gratis/vista-superior-lapices-clips-espacio-copia_8852256.htm#fromView=image_search_similar&page=3&position=1&uuid=54a8cc55-3529-43e0-91d6-66f41a252e2a&query=fondo+registrarse+universidad
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/vector-gratis/zoom-velocidad-tubo-luz-azul-abstracto-tecnologia-fondo-negro_32947939.htm#fromView=image_search_similar&page=1&position=32&uuid=2e117b63-eddd-4d54-8d4f-c5a328b65db8&query=fondo+login+ciberseguridad
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/foto-gratis/vista-superior-teclado-escritorio-notebook-planta-suculenta_6607587.htm#fromView=image_search_similar&page=3&position=17&uuid=db87fedd-c891-4ed0-b419-c51dce023178&query=asignar+curso+minimalista+fondo
Freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/foto-gratis/universidad-harvard-cambridge-ee-uu_8565573.htm#fromView=search&page=1&position=26&uuid=efc7ea68-6ca1-4126-9981-7f3b0855dd20&query=universidad
novato, P. (4 de septiembre de 2019). youtube. Obtenido de Programación novato: https://www.youtube.com/watch?v=97nO4-zdviA&list=PLCTD_CpMeEKTT-qEHGqZH3fkBgXH4GOTF
TodoCode. (6 de octubre de 2024). youtube. Obtenido de https://www.youtube.com/watch?v=qxXcI56NfnE
TX, P. (10 de febrero de 2021). youtube. Obtenido de https://www.youtube.com/watch?v=AHKUFs5brOc&list=PLC8aeqj9UWGOaKEz2_AjY5o0-a8wiphc0
*/