//Universidad Estatal a Distancia
//Vicerrectoría de Docencia
//Escuela de Ciencias Exactas y Naturales
//Cátedra de Desarrollo de sistemas
//Asignatura: SISTEMAS OPERATIVOS
//Código: 00881
// II CUATRIMESTRE 2025
//Estudiante: Héctor Andrés Arrieta Sancho
//Cédula: 114070263
//Proyecto final sistemas operativos
/// Proyecto de aula virtual que permite el registro, asignación y consulta de cursos,
/// gestionando accesos diferenciados para administradores y estudiantes.

package Ventanas;


public class VentanaAulaVirtual extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAulaVirtual
     */
    
    private String tipoUsuario; // "admin" o "estudiante"

    public VentanaAulaVirtual() {
        initComponents();
        setTitle("Aula Virtual - Entorno Universitario UNED"); // Título de la ventana
        setResizable(false); // No permitir cambiar el tamaño
        setLocationRelativeTo(null); // Centrar la ventana

        // Cargar fondo, si usas imagen de fondo como en otras ventanas
        try {
    Utilidades.UtilidadesGUI.configurarVentana(this, "/imagenes/fondoaulavirtual.jpg");
    } catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar fondo: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}

    }

    
///
///constructor que recibe el tipo de usuario para controlar acceso
///
public VentanaAulaVirtual(String tipoUsuario) {
    this(); // Llama al constructor original
    this.tipoUsuario = tipoUsuario;

    ///
    ///muestra el nombre del estudiante en el label si es estudiante
    ///
    if ("estudiante".equals(tipoUsuario) && LogicaDeNegocio.SesionEstudiante.obtenerEstudiante() != null) {
        lblUsuarioActual.setText("Bienvenido estudiante: " + LogicaDeNegocio.SesionEstudiante.obtenerEstudiante().getNombre());
    } else if ("admin".equals(tipoUsuario)) {
        lblUsuarioActual.setText("Bienvenido señor administrador");
    }

    ///
    ///activar o desactivar botones según el tipo de usuario
    ///
    if ("admin".equals(tipoUsuario)) {
        btnAsignarCursos.setEnabled(false); // Solo para estudiantes
        btnRegistrarCursos.setEnabled(true);
    } else {
        btnAsignarCursos.setEnabled(true);
        btnRegistrarCursos.setEnabled(false); // Solo para admin
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAsignarCursos = new javax.swing.JButton();
        btnRegistrarCursos = new javax.swing.JButton();
        btnBuscarEstudiantes = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblUsuarioActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 3, 24)); // NOI18N
        jLabel1.setText("Aula virtual UNED");

        btnAsignarCursos.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        btnAsignarCursos.setText("Asignar cursos");
        btnAsignarCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsignarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCursosActionPerformed(evt);
            }
        });

        btnRegistrarCursos.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        btnRegistrarCursos.setText("Registrar cursos");
        btnRegistrarCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCursosActionPerformed(evt);
            }
        });

        btnBuscarEstudiantes.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        btnBuscarEstudiantes.setText("Buscar estudiantes y cursos");
        btnBuscarEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudiantesActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        btnVolver.setText("Cerrar sesión");
        btnVolver.setActionCommand("Cerrar sesión");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblUsuarioActual.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        lblUsuarioActual.setForeground(new java.awt.Color(0, 153, 51));
        lblUsuarioActual.setText("\"usuario\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarCursos)
                            .addComponent(btnAsignarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnBuscarEstudiantes)))
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(lblUsuarioActual)
                .addGap(18, 18, 18)
                .addComponent(btnAsignarCursos)
                .addGap(34, 34, 34)
                .addComponent(btnRegistrarCursos)
                .addGap(35, 35, 35)
                .addComponent(btnBuscarEstudiantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnVolver))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCursosActionPerformed
        AsignacionCursos ventana = new AsignacionCursos(tipoUsuario); 
    ventana.setVisible(true);

    //oculta esta ventana temporalmente
    this.setVisible(false);

    //al cerrar la ventana de asignación, vuelve a esta
    ventana.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            setVisible(true);
        }
    });
    }//GEN-LAST:event_btnAsignarCursosActionPerformed

    private void btnRegistrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCursosActionPerformed
       RegistroCursos ventana = new RegistroCursos(tipoUsuario); // Crea la nueva ventana
    ventana.setVisible(true); // La muestra

    this.setVisible(false); // Oculta la actual

    // Si se cierra RegistroCursos, volver a esta
    ventana.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            setVisible(true);
        }
    });
    }//GEN-LAST:event_btnRegistrarCursosActionPerformed

    private void btnBuscarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudiantesActionPerformed
         BuscarEstudiante ventana = new BuscarEstudiante(tipoUsuario); // Crea la nueva ventana
    ventana.setVisible(true);

    // Oculta esta ventana temporalmente
    this.setVisible(false);

    ventana.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            setVisible(true);
        }
    });
    }//GEN-LAST:event_btnBuscarEstudiantesActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
      this.setVisible(false); //oculta esta ventana
    VentanaPrincipal menu = new VentanaPrincipal(); // Crea el menú principal
    menu.setVisible(true); // Muestra el menú principal

    // Si cierran el menú principal volver al aula virtual
    menu.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            setVisible(true); //vuelve a mostrar esta ventana
        }
    });
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAulaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAulaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAulaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAulaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAulaVirtual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarCursos;
    private javax.swing.JButton btnBuscarEstudiantes;
    private javax.swing.JButton btnRegistrarCursos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUsuarioActual;
    // End of variables declaration//GEN-END:variables
}
/*
Referencias bibliográficas
Academy, E. (24 de abril de 2023). youtube. Obtenido de https://www.youtube.com/watch?v=SXIOxvxWf7A
BOS, A. S. (2024). SISTEMAS OPERATIVOS. México: Pearson Educación de méxico.
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/vector-gratis/personas-que-van-universidad-fondo-rosa_9057638.htm#fromView=search&page=1&position=43&uuid=ed7ad1f5-f8a4-46b1-83c2-9724be9869a6&query=entorno+estudiantil+animado+minimalista
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/foto-gratis/concepto-escritorio-vista-superior-cafe_9216574.htm#fromView=image_search_similar&page=1&position=7&uuid=54a8cc55-3529-43e0-91d6-66f41a252e2a&query=fondo+registrarse+universidad
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/foto-gratis/vista-superior-lapices-clips-espacio-copia_8852256.htm#fromView=image_search_similar&page=3&position=1&uuid=54a8cc55-3529-43e0-91d6-66f41a252e2a&query=fondo+registrarse+universidad
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/vector-gratis/zoom-velocidad-tubo-luz-azul-abstracto-tecnologia-fondo-negro_32947939.htm#fromView=image_search_similar&page=1&position=32&uuid=2e117b63-eddd-4d54-8d4f-c5a328b65db8&query=fondo+login+ciberseguridad
freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/foto-gratis/vista-superior-teclado-escritorio-notebook-planta-suculenta_6607587.htm#fromView=image_search_similar&page=3&position=17&uuid=db87fedd-c891-4ed0-b419-c51dce023178&query=asignar+curso+minimalista+fondo
Freepik. (2025). www.freepik.com. Obtenido de https://www.freepik.es/foto-gratis/universidad-harvard-cambridge-ee-uu_8565573.htm#fromView=search&page=1&position=26&uuid=efc7ea68-6ca1-4126-9981-7f3b0855dd20&query=universidad
novato, P. (4 de septiembre de 2019). youtube. Obtenido de Programación novato: https://www.youtube.com/watch?v=97nO4-zdviA&list=PLCTD_CpMeEKTT-qEHGqZH3fkBgXH4GOTF
TodoCode. (6 de octubre de 2024). youtube. Obtenido de https://www.youtube.com/watch?v=qxXcI56NfnE
TX, P. (10 de febrero de 2021). youtube. Obtenido de https://www.youtube.com/watch?v=AHKUFs5brOc&list=PLC8aeqj9UWGOaKEz2_AjY5o0-a8wiphc0
*/